

---
- name: Remove old Docker versions
  hosts: all
  become: true
  tasks:
    - apt: 
        name: "{{item}}"
        state: absent
      with_items:
        - docker
        - docker-engine
        - docker.io

- name: Install Docker and role dependencies
  hosts: all
  tasks:
    - apt:
        name: "{{item}}"
        state: present
        install_recommends: False
      with_items:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - curl

# - name: Get upstream APT GPG key
#   hosts: all
#   tasks:
#   - apt_key:
#       id: "{{ docker_apt_key }}"
#       keyserver: "{{ ansible_local.core.keyserver
#                       if (ansible_local|d() and ansible_local.core|d() and
#                           ansible_local.core.keyserver)
#                       else 'hkp://pool.sks-keyservers.net' }}"
#       state: "present"


# - name: Configure upstream APT repository
#   apt_repository:
#     # docker_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
#     repo: "{{ docker_repository }}"
#     state: "present"
#     update_cache: True
        
