---
- name: Setting Facts
  hosts: all
  tasks:
  - set_fact:
      docker_edition: ce
      docker_channel: stable
      docker_version: 17.12.0
      docker_apt_cache_time: 86400
      docker_users: ["packer"]

- name: Remove old Docker versions
  hosts: all
  become: true
  tasks:
    - package: 
        name: "{{item}}"
        state: absent
      with_items:
        - docker
        - docker-engine
        - docker.io

- name: Install Docker and role dependencies
  hosts: all
  tasks:
    - package:
        name: "{{item}}"
        state: present
        install_recommends: False
      with_items:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - curl

# - name: Get upstream APT GPG key
#   hosts: all
#   tasks:
#   - apt_key:
#       id: "{{ docker_apt_key }}"
#       keyserver: "{{ ansible_local.core.keyserver
#                       if (ansible_local|d() and ansible_local.core|d() and
#                           ansible_local.core.keyserver)
#                       else 'hkp://pool.sks-keyservers.net' }}"
#       state: "present"


- name: Configure upstream APT repository
  hosts: all
  tasks:
  - apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_channel }}"
      state: "present"
      update_cache: True

- name: Install Docker
  hosts: all
  become: true
  tasks:
    - package:
        name: "docker-{{ docker_edition }}={{ docker_version }}~{{ docker_edition }}-0~{{ ansible_distribution | lower }}"
        state: "present"
        update_cache: True
        install_recommends: False
        cache_valid_time: "{{ docker_apt_cache_time }}"

- name: Add Users to "docker" group
  hosts: all
  become: true
  tasks:
    - user:
        name: "{{item}}"
        groups: "docker"
        append: True
      with_items: "{{docker_users}}"
      when: docker_users
        
